version: '3.1'
services:
  adsmsg:
    build: .
    image: adsmsg:latest
    container_name: adsmsg
    volumes:
     - ./:/app
    networks:
      - adsmsg
    stdin_open: true
    tty: true
    entrypoint: make
networks:
  adsmsg:
    driver: bridge
